services:
  db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ferdian
      - POSTGRES_PASSWORD=password
    volumes:
      - type: volume
        source: db-volume
        target: "/var/lib/pgsql/data"
        read_only: false

volumes:
  db-volume:
    name: postgresql-data
